name: Build-Test-Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # 建立 Release 需要 write 權限

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.30' # 可省略用預設

      - name: Build (bun i + ncc)
        run: |
          npm run build
          # 若你的 build 沒產出檔案，保險起見放一個檔案到 dist 方便釋出
          mkdir -p dist
          [ -f dist/build.txt ] || echo "artifact built at $(date)" > dist/build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Setup Node (for tests)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Automated Tests
        run: |
          echo "Running automated tests..."
          npm test || (echo "❌ Tests failed" && exit 1)

  release:
    name: Release (dev)
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    if: ${{ success() }}   # 只有測試全過才跑
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-${{ github.run_number }}
          name: "Dev Build #${{ github.run_number }}"
          body: "Automated release after successful tests"
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
